spd = 0.25;
letters = 0;
// backslash n = line break! :)
text = "Press e once you're ready to guess.\nPress q to go back."
length = string_length(text);
text_current = "";
w = 0;
h = 0;
border = 10; 
