spd = 0.25;
letters = 0;
// backslash n = line break! :)
text = "Decipher the code to discover what color \nthe murderer was wearing"
length = string_length(text);
text_current = "";
w = 0;
h = 0;
border = 10; 
