spd = 0.25;
letters = 0;
// backslash n = line break! :)
text = "Work closely with your partner \nin order to solve the murder."
length = string_length(text);
text_current = "";
w = 0;
h = 0;
border = 10; 
